C
C    common block for epics beam parameters
C
       real x_2c21, y_2c21, i_2c21,
     +      x_2c24, y_2c24, i_2c24,
     +      x_2h01, y_2h01, i_2h01,
     +      halla_energy, hallb_energy, hallc_energy,
     +      halla_df, hallb_df, hallc_df,
     +      halla_current, hallb_current, hallc_current, fcup_current

	common/BEAM_PARAMS/x_2c21, y_2c21, i_2c21,
     +      x_2c24, y_2c24, i_2c24,
     +      x_2h01, y_2h01, i_2h01,
     +      halla_energy, hallb_energy, hallc_energy,
     +      halla_df, hallb_df, hallc_df,
     +      halla_current, hallb_current, hallc_current, fcup_current

