/* This file generated by inc2h.pl on Mon Aug 24 18:06:19 EDT 1998 */

/* C representation of dc_tcl common block */

/* MUST BE KEPT IN SYNCH WITH dc_tcl.inc */


typedef struct {

   double dc_xvst_default_slope;
   double dc_xvst_n_power;
   double dc_xvst_m_power;
   double dc_sigma_doca[6];
   double dc_efficiency;
   double dc_trig_time;
   double dc_reg_pulser_time[3];
   double dc_vel_prop;
   int dc_xvst_choice;
   double dc_mult_sigma[6];

} dc_tcl_t;

extern dc_tcl_t dc_tcl_;

