/*
   endianConverterAuto.h --- endian converter

   this file is automatically generated by 'endianStubGen.perl'
*/


#include <itape.h>
#include <ntypes.h>


extern int endian_convertType1_INTARRAY_t(void*dptr,int dlength);
extern int endian_convertTypeN_INTARRAY_t(void*dptr,int dcount);
extern int endian_convertType1_NOCONVERT_t(void*dptr,int dlength);
extern int endian_convertTypeN_NOCONVERT_t(void*dptr,int dcount);
extern int endian_convertType1_double(double*dptr,int dlength);
extern int endian_convertTypeN_double(double*dptr,int dcount);
extern int endian_convertType1_uint16(uint16*dptr,int dlength);
extern int endian_convertTypeN_uint16(uint16*dptr,int dcount);
extern int endian_convertType1_uint32(uint32*dptr,int dlength);
extern int endian_convertTypeN_uint32(uint32*dptr,int dcount);
extern int endian_convertType1_uint8(uint8*dptr,int dlength);
extern int endian_convertTypeN_uint8(uint8*dptr,int dcount);
extern int endian_convertType1_vector3_t(vector3_t*dptr,int dlength);
extern int endian_convertTypeN_vector3_t(vector3_t*dptr,int dcount);
extern int endian_convertType1_vector4_t(vector4_t*dptr,int dlength);
extern int endian_convertTypeN_vector4_t(vector4_t*dptr,int dcount);



/* end file */
