/* This file generated by inc2h.pl on Fri Apr 16 16:16:37 EDT 1999 */

/* C representation of evnt_par common block */

/* MUST BE KEPT IN SYNCH WITH evnt_par.inc */

typedef struct {
  int   maxel;
  float cut_t_sccc;
  float cut_t_scec;
  float cut_b_sc;
  float cut_b_ec;
  float cut_t_eccc;
  float sampl_frac;
  float sigma_etrk;
  float m2_ecel_cut;
  float m3_ecel_cut;
  float etot_ecel_cut;
  float eio_ecel_cut;
  float trkcc_match;
  float trksc_match;
  float trkec_match;
  float trklec_match;
  float eccc_match;
  float ecsc_match;
  float ecec_match;
  int   photon_trig_type;
  float bt_Z_center;
  float leccc_match;
  float lecsc_match;
  float lecec_match;
  int   trigger_particle;
  int   neut_trigg_photon; 
  int   trigger_particle_s;
  float mtrigg;
  float qtrigg;
  float mtrigg_s;
  float qtrigg_s;
  float st_tagger_match;
  int iRFpcorr;
} evnt_par_t;

extern evnt_par_t evnt_par_;

