#define GROUP_BMPR 10 /* clasBMPR_t (see bosddl.h) */
#define GROUP_BREP 20 /* clasBREP_t (see bosddl.h) */
#define GROUP_CALL 30 /* clasCALL_t (see bosddl.h) */
#define GROUP_CC01 50 /* clasCC01_t (see bosddl.h) */
#define GROUP_CCDI 70 /* clasCCDI_t (see bosddl.h) */
#define GROUP_CCH1 90 /* clasCCH1_t (see bosddl.h) */
#define GROUP_CCH2 100 /* clasCCH2_t (see bosddl.h) */
#define GROUP_CCMT 110 /* clasCCMT_t (see bosddl.h) */
#define GROUP_CCPB 120 /* clasCCPB_t (see bosddl.h) */
#define GROUP_CCPE 130 /* clasCCPE_t (see bosddl.h) */
#define GROUP_CCRC 140 /* clasCCRC_t (see bosddl.h) */
#define GROUP_CHI2 160 /* clasCHI2_t (see bosddl.h) */
#define GROUP_CPED 170 /* clasCPED_t (see bosddl.h) */
#define GROUP_ECPC 180 /* clasECPC_t (see bosddl.h) */
#define GROUP_ECPE 190 /* clasECPE_t (see bosddl.h) */
#define GROUP_CL01 200 /* clasCL01_t (see bosddl.h) */
#define GROUP_DCDW 230 /* clasDCDW_t (see bosddl.h) */
#define GROUP_DCGM 240 /* clasDCGM_t (see bosddl.h) */
#define GROUP_DCGW 250 /* clasDCGW_t (see bosddl.h) */
#define GROUP_DCPB 270 /* clasDCPB_t (see bosddl.h) */
#define GROUP_DCV1 280 /* clasDCV1_t (see bosddl.h) */
#define GROUP_DCV2 290 /* clasDCV2_t (see bosddl.h) */
#define GROUP_DCV3 300 /* clasDCV3_t (see bosddl.h) */
#define GROUP_DDLY 310 /* clasDDLY_t (see bosddl.h) */
#define GROUP_DGEO 320 /* clasDGEO_t (see bosddl.h) */
#define GROUP_DHCL 330 /* clasDHCL_t (see bosddl.h) */
#define GROUP_DOCA 340 /* clasDOCA_t (see bosddl.h) */
#define GROUP_DPSP 350 /* clasDPSP_t (see bosddl.h) */
#define GROUP_DSPC 360 /* clasDSPC_t (see bosddl.h) */
#define GROUP_DSPS 370 /* clasDSPS_t (see bosddl.h) */
#define GROUP_DSTC 380 /* clasDSTC_t (see bosddl.h) */
#define GROUP_DTRK 390 /* clasDTRK_t (see bosddl.h) */
#define GROUP_EC01 410 /* clasEC01_t (see bosddl.h) */
#define GROUP_EC1P 430 /* clasEC1P_t (see bosddl.h) */
#define GROUP_EC1R 440 /* clasEC1R_t (see bosddl.h) */
#define GROUP_ECCA 450 /* clasECCA_t (see bosddl.h) */
#define GROUP_ECCL 460 /* clasECCL_t (see bosddl.h) */
#define GROUP_ECCT 470 /* clasECCT_t (see bosddl.h) */
#define GROUP_ECDI 480 /* clasECDI_t (see bosddl.h) */
#define GROUP_ECHB 510 /* clasECHB_t (see bosddl.h) */
#define GROUP_ECMT 520 /* clasECMT_t (see bosddl.h) */
#define GROUP_ECP1 540 /* clasECP1_t (see bosddl.h) */
#define GROUP_ECPB 550 /* clasECPB_t (see bosddl.h) */
#define GROUP_ECPI 560 /* clasECPI_t (see bosddl.h) */
#define GROUP_ECPO 570 /* clasECPO_t (see bosddl.h) */
#define GROUP_ECRB 580 /* clasECRB_t (see bosddl.h) */
#define GROUP_EID0 600 /* clasEID0_t (see bosddl.h) */
#define GROUP_EPIC 610 /* clasEPIC_t (see bosddl.h) */
#define GROUP_EVNT 620 /* clasEVNT_t (see bosddl.h) */
#define GROUP_FBPM 630 /* clasFBPM_t (see bosddl.h) */
#define GROUP_GPAR 640 /* clasGPAR_t (see bosddl.h) */
#define GROUP_G1SL 650 /* clasG1SL_t (see bosddl.h) */
#define GROUP_G2SL 660 /* clasG2SL_t (see bosddl.h) */
#define GROUP_G3SL 670 /* clasG3SL_t (see bosddl.h) */
#define GROUP_G4SL 680 /* clasG4SL_t (see bosddl.h) */
#define GROUP_HBER 690 /* clasHBER_t (see bosddl.h) */
#define GROUP_HBID 700 /* clasHBID_t (see bosddl.h) */
#define GROUP_HBLA 710 /* clasHBLA_t (see bosddl.h) */
#define GROUP_HBTB 720 /* clasHBTB_t (see bosddl.h) */
#define GROUP_HBTR 730 /* clasHBTR_t (see bosddl.h) */
#define GROUP_HCAL 740 /* clasHCAL_t (see bosddl.h) */
#define GROUP_HDPL 750 /* clasHDPL_t (see bosddl.h) */
#define GROUP_HEAD 760 /* clasHEAD_t (see bosddl.h) */
#define GROUP_HEVT 770 /* clasHEVT_t (see bosddl.h) */
#define GROUP_LCDI 790 /* clasLCDI_t (see bosddl.h) */
#define GROUP_LCPB 800 /* clasLCPB_t (see bosddl.h) */
#define GROUP_KFIT 810 /* clasKFIT_t (see bosddl.h) */
#define GROUP_MCEV 820 /* clasMCEV_t (see bosddl.h) */
#define GROUP_MCTK 830 /* clasMCTK_t (see bosddl.h) */
#define GROUP_MCVX 840 /* clasMCVX_t (see bosddl.h) */
#define GROUP_PART 850 /* clasPART_t (see bosddl.h) */
#define GROUP_PTDB 880 /* clasPTDB_t (see bosddl.h) */
#define GROUP_RGLK 900 /* clasRGLK_t (see bosddl.h) */
#define GROUP_RUNC 910 /* clasRUNC_t (see bosddl.h) */
#define GROUP_RTSL 920 /* clasRTSL_t (see bosddl.h) */
#define GROUP_SCMD 980 /* clasSCMD_t (see bosddl.h) */
#define GROUP_SCPB 1000 /* clasSCPB_t (see bosddl.h) */
#define GROUP_SCPE 1010 /* clasSCPE_t (see bosddl.h) */
#define GROUP_SCDI 1040 /* clasSCDI_t (see bosddl.h) */
#define GROUP_SCMT 1050 /* clasSCMT_t (see bosddl.h) */
#define GROUP_SCMW 1060 /* clasSCMW_t (see bosddl.h) */
#define GROUP_SCRC 1070 /* clasSCRC_t (see bosddl.h) */
#define GROUP_SPAR 1080 /* clasSPAR_t (see bosddl.h) */
#define GROUP_STPE 1120 /* clasSTPE_t (see bosddl.h) */
#define GROUP_STPB 1130 /* clasSTPB_t (see bosddl.h) */
#define GROUP_S1ST 1160 /* clasS1ST_t (see bosddl.h) */
#define GROUP_SYNC 1170 /* clasSYNC_t (see bosddl.h) */
#define GROUP_TACO 1180 /* clasTACO_t (see bosddl.h) */
#define GROUP_TAGE 1190 /* clasTAGE_t (see bosddl.h) */
#define GROUP_TAGI 1200 /* clasTAGI_t (see bosddl.h) */
#define GROUP_TAGR 1210 /* clasTAGR_t (see bosddl.h) */
#define GROUP_TAGT 1220 /* clasTAGT_t (see bosddl.h) */
#define GROUP_TBER 1230 /* clasTBER_t (see bosddl.h) */
#define GROUP_TBID 1240 /* clasTBID_t (see bosddl.h) */
#define GROUP_TBLA 1250 /* clasTBLA_t (see bosddl.h) */
#define GROUP_TBTR 1260 /* clasTBTR_t (see bosddl.h) */
#define GROUP_TCSB 1270 /* clasTCSB_t (see bosddl.h) */
#define GROUP_TDPL 1280 /* clasTDPL_t (see bosddl.h) */
#define GROUP_TGBI 1290 /* clasTGBI_t (see bosddl.h) */
#define GROUP_TGPB 1300 /* clasTGPB_t (see bosddl.h) */
#define GROUP_TGS 1310 /* clasTGS_t (see bosddl.h) */
#define GROUP_TRGS 1320 /* clasTRGS_t (see bosddl.h) */
#define GROUP_TRKS 1330 /* clasTRKS_t (see bosddl.h) */
#define GROUP_TRGT 1340 /* clasTRGT_t (see bosddl.h) */
#define GROUP_UNUS 1350 /* clasUNUS_t (see bosddl.h) */
#define GROUP_VERT 1360 /* clasVERT_t (see bosddl.h) */
#define GROUP_MVRT 1370 /* clasMVRT_t (see bosddl.h) */
#define GROUP_MTRK 1380 /* clasMTRK_t (see bosddl.h) */
#define GROUP_SGMP 1390 /* clasSGMP_t (see bosddl.h) */
#define GROUP_CLST 1400 /* clasCLST_t (see bosddl.h) */
