#
# clasbanks.ddl makefile  This Makefile will eventually automatically
# build $CLAS_PARMS/clasbanks.ddl, $CLAS_PARMS/rawdata.ddl and
# $CLAS_PARMS/clas_dst.ddl..... whenever a bank has been altered
#
# persently it does nothing.
#
#  The "lib"  and "exe" targets are required by the make system 
#
lib:

exe:

clean:

help:

FORCE = DUMMY
DUMMY :



# end of bankdefs makefile